server:
  port : 5000
  error:
    include-message : always

spring:
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    username : root
    password : password
    url : jdbc:mysql://localhost:3306/social_network_springboot
  jpa:
    hibernate:
      ddl-auto : update
      # ddl-auto : create-drop
      show-sql : true
